# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub }:
{
  edopro = {
    pname = "edopro";
    version = "39.3.1";
    src = fetchurl {
      url = "https://github.com/ProjectIgnis/edopro-assets/releases/download/39.3.1/ProjectIgnis-EDOPro-39.3.1-linux.tar.gz";
      sha256 = "sha256-c7E7k6mKfXltiknR1JAsC78/q4+ypjJ19B2PBJX2nE4=";
    };
  };
  eontimer = {
    pname = "eontimer";
    version = "d53e42a508de4003b719791ce36e37a8f49dbfc9";
    src = fetchFromGitHub ({
      owner = "dylmeadows";
      repo = "EonTimer";
      rev = "d53e42a508de4003b719791ce36e37a8f49dbfc9";
      fetchSubmodules = false;
      sha256 = "sha256-jelFKEaifMOtKWJIkJvDMoP+dsQOfNPkx9YjyK4HVj4=";
    });
  };
  eontimer-qtsass = {
    pname = "eontimer-qtsass";
    version = "0.3.0";
    src = fetchurl {
      url = "https://pypi.io/packages/source/q/qtsass/qtsass-0.3.0.tar.gz";
      sha256 = "sha256-J8SfY86p4joLlhj3H0pOmSgzzRz9947YMsac7qHeH+c=";
    };
  };
  gcs = {
    pname = "gcs";
    version = "v4.37.1";
    src = fetchFromGitHub ({
      owner = "richardwilkes";
      repo = "gcs";
      rev = "v4.37.1";
      fetchSubmodules = false;
      sha256 = "sha256-znN2tBUp0yAvM6E4eTcfmV3KmzyYlrRMLZgc/Fg9tFc=";
    });
  };
  maptool = {
    pname = "maptool";
    version = "1.11.5";
    src = fetchFromGitHub ({
      owner = "RPTools";
      repo = "maptool";
      rev = "1.11.5";
      fetchSubmodules = false;
      sha256 = "sha256-8X9rPEsfU6f+jMWGfcgkMVW0/b+2+NlPWManhO7KQpk=";
    });
  };
  maptool-dicelib = {
    pname = "maptool-dicelib";
    version = "1.8.3";
    src = fetchFromGitHub ({
      owner = "RPTools";
      repo = "dicelib";
      rev = "1.8.3";
      fetchSubmodules = false;
      sha256 = "sha256-2yjKYHsSwBfkCe8UobWzBV7hDeU9OmsC1yrhVLR97mI=";
    });
  };
  pokefinder = {
    pname = "pokefinder";
    version = "8cc4f370621e18499e958b3dba1a4aa2a3ab80ec";
    src = fetchFromGitHub ({
      owner = "Admiral-Fish";
      repo = "PokeFinder";
      rev = "8cc4f370621e18499e958b3dba1a4aa2a3ab80ec";
      fetchSubmodules = true;
      sha256 = "sha256-XojkmEnHeilhRZ6OQ46Qd0yJLHnAAQyvdS4zAlZ2xTw=";
    });
  };
}
